name: TokenEnchant
version: 1.0
main: me.ayush_03.tokenenchant.Main
author: Ayush_03
description: A custom enchant plugin for Jim

commands:
    tokens:
       usage: /tokens
       description: Main command.